"""encryted assignments at rest

Revision ID: 339efae9108e
Revises: 189b28e5cf7c
Create Date: 2025-12-19 04:04:10.768435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339efae9108e'
down_revision = '189b28e5cf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_ciphertext', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_ciphertext')

    # ### end Alembic commands ###
