"""initial

Revision ID: cbb4d6b911d3
Revises: 
Create Date: 2025-12-18 04:10:04.762126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb4d6b911d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_state'))
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passkey_hash', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('reset_requested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['participants.id'], name=op.f('fk_participants_assigned_to_id_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants')),
    sa.UniqueConstraint('email', name=op.f('uq_participants_email')),
    sa.UniqueConstraint('name', name=op.f('uq_participants_name'))
    )
    op.create_table('exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['giver_id'], ['participants.id'], name=op.f('fk_exclusions_giver_id_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['participants.id'], name=op.f('fk_exclusions_receiver_id_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusions')),
    sa.UniqueConstraint('giver_id', 'receiver_id', name='uq_exclusion_giver_receiver')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusions')
    op.drop_table('participants')
    op.drop_table('assignment_state')
    # ### end Alembic commands ###
