"""empty message

Revision ID: f7f04cfc881e
Revises: 
Create Date: 2025-12-18 02:14:06.657551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f04cfc881e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['giver_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giver_id', 'receiver_id', name='uq_exclusion_giver_receiver')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusions')
    # ### end Alembic commands ###
